version: '3'
services:
    mysql:
        container_name: dc_mysql
        image: mysql:5.6
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${MYSQL_PORT}:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_VOLUME}:/docker-entrypoint-initdb.d/
        networks:
            - backend
      
    dc_redis:
        container_name: dc_redis
        image: redis:2.6.17
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - ${REDIS_VOLUME}:/usr/local/etc/redis/redis.conf
        networks:
            - backend
  
    dc_solr:
        container_name: dc_solr
        build: ./docker/solr
        ports:
            - ${SOLR_PORT}:8983
        volumes:
            - ${SOLR_VOLUME}:/opt/solr/solr/collection1/conf
        networks:
            - backend   

    dc_backend:
        env_file: .env
        container_name: dc_backend
        depends_on:
            - mysql
            - dc_redis
            - dc_solr
        build: ./backend
        ports:
            - ${BACKEND_PORT}:8080
        links:
            - mysql:container_mysql
            - dc_redis:container_redis
            - dc_solr:container_solr
        networks:
            - backend
        environment:
            - WAIT_HOSTS=mysql:3306

      


networks:
    backend:
        driver: "bridge"