version: '3'
services:       
    dc_frontend:
        container_name: dc_frontend
        stdin_open: true        
        depends_on:
            - dc_backend
        build: 
            context: ./frontend/
            dockerfile: Dockerfile.prod
        ports:
            - ${FRONTEND_PORT}:80
        links:
            - dc_backend:container_backend
        networks:
            - backend
            
    dc_admin:
        container_name: dc_admin
        stdin_open: true        
        depends_on:
            - dc_backend
        build: 
            context: ./admin/
            dockerfile: Dockerfile.prod
        ports:
            - ${ADMIN_PORT}:80
        links:
            - dc_backend:container_backend
        networks:
            - backend


networks:
    backend:
        driver: "bridge"